'use client';

import '~/styles/globals.css';

import {GeistSans} from 'geist/font/sans';
import {ProcessedSubjectImagePassingContext} from '~/components/ProcessedSubjectImagePassingContext';
import {useState} from 'react';

/* TODO:
   export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{rel: 'icon', url: '/favicon.ico'}],
};*/

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  const [processedSubjectImage, setProcessedSubjectImage] = useState<Blob|undefined>();

  return (
    <html lang='en' className={`${GeistSans.variable}`}>
      <ProcessedSubjectImagePassingContext.Provider value={{processedSubjectImage, setProcessedSubjectImage}}>
        <body>{children}</body>
      </ProcessedSubjectImagePassingContext.Provider>
    </html>
  );
}
